spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meeteam
    username: meeteam
    password: meeteam123!!!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
    database-platform: org.hibernate.dialect.MySQLDialect
jwt:
  secret: ${JWT_SECRET}