# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest
    steps:
      - name: ssh 원격 접속
        uses: appleboy/ssh-action@v1.0.3
        env:
          APPLICATION_DEV_YML: ${{secrets.APPLICATION_DEV_YML}}
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ${{ secrets.EC2_USERNAME}}
          key: ${{ secrets.EC2_PRIVATE_KEY}}
          envs: APPLICATION_DEV
          script_stop: true
          script: |
            cd /home/ubuntu/server/meeTeam
            rm -rf src/main/resources/application-dev.yml
            git pull origin main
            echo "$APPLICATION_DEV" > src/main/resources/application-dev.yml
            ./gradlew clean build -x test
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log > 2&1 &